from collections.abc import AsyncIterator
from typing import Protocol, runtime_checkable


@runtime_checkable
class LLMClient(Protocol):
    async def complete(self, messages: list[dict], max_tokens: int) -> str: ...

    def stream_complete(self, messages: list[dict], max_tokens: int) -> AsyncIterator[str]: ...

    async def ping(self) -> bool: ...

    async def warmup(self) -> None: ...

    async def list_models(self) -> list[str]: ...

    async def close(self) -> None: ...
